declare module "virtual:purplepanda/islands" {
  import type { ComponentConfig } from "@puckeditor/core";

  // Generated by the `purple-panda-islands` Vite plugin in astro.config.ts.
  const loaders: Record<string, () => Promise<ComponentConfig>>;
  export default loaders;
}
